# Generated by Django 3.2.15 on 2022-09-19 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductManager', '0002_favourite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favourite',
        ),
    ]
